//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kulala.Learning.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class book250
    {
        public long id { get; set; }
        public string title { get; set; }
        public Nullable<decimal> score { get; set; }
        public string book_link { get; set; }
        public string Img_link { get; set; }
        public string author { get; set; }
        public string press { get; set; }
        public string time { get; set; }
        public string money { get; set; }
        public Nullable<decimal> num { get; set; }
        public string jieshao { get; set; }
    }
}
